method: manifold_mall_td
dataset:
    path: ./data/MALL/trans_visual_dataset.pkl
    train_path: ./data/MALL/vsta_visual_dataset.pkl 
    # path: ./data/PTD/resnet50_visual_dataset.pkl 
st_rerank: 
  enable: False
rerank:
  enable: False
  k1: 1
  k2: 2
  lambda: 0.8
adj2path: manifold
dim: 2048
seed: 1
# cluster_threshold: 0.05
# cluster_threshold: 0.07
# cluster_threshold: 0.09
# cluster_threshold: 0.13
cluster_threshold: 0.13
manifold:
  # alpha: 0.9
  # alpha: 0.3
  # alpha: 0.5
  alpha: 0.9
  eta : 3.1415926