method: manifold_ptd
dataset:
    # path: ./data/market/vsta_visual_dataset.pkl
    path: ./data/PTD/mgn_visual_dataset.pkl 
st_rerank: 
  enable: False
rerank:
  enable: False
  k1: 1
  k2: 2
  lambda: 0.8
seed: 3
adj2path: manifold
dim: 2048
cluster_threshold: 0.22
manifold:
  alpha: 0.04
  eta: 0.01



  