method: manifold_mall_td
dataset:
    path: ./data/MALL/vsta_visual_dataset.pkl
    train_path: ./data/MALL/vsta_visual_dataset.pkl 
st_rerank: 
  enable: False
rerank:
  enable: False
  k1: 1
  k2: 2
  lambda: 0.8
seed: 3
adj2path: manifold
dim: 2048
#BEST PTR+:
cluster_threshold: 0.6
#best PTR:
# cluster_threshold: 0.386
manifold:
  alpha: 0.3
  # alpha: 0.38
  eta: 3
  # eta: 1.11